---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install basic dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - wget
    - unzip
    - software-properties-common
    - python3-pip
    - apt-transport-https
    - ca-certificates
